# Generated by Django 2.1.7 on 2019-03-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.CharField(blank=True, default='Write about yourself', max_length=200, null=True, verbose_name='Short Bio'),
        ),
    ]
