# Generated by Django 2.1.7 on 2019-03-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.AddField(
            model_name='customuser',
            name='blood_group',
            field=models.CharField(choices=[('B+', 'B+'), ('A-', 'A-'), ('A+', 'A+'), ('O+', 'O+'), ('O-', 'O-')], default='B+', max_length=32),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AddField(
            model_name='customuser',
            name='university',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
