# Generated by Django 2.1.2 on 2019-03-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190323_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='university',
        ),
        migrations.AddField(
            model_name='customuser',
            name='university_name',
            field=models.CharField(default=0, max_length=17),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=17),
        ),
    ]
