# Generated by Django 2.1.2 on 2019-03-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190323_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='DayCount',
            field=models.IntegerField(blank=True, default=120, max_length=32),
        ),
    ]
