# Generated by Django 2.1.2 on 2019-03-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='DayCount',
            field=models.IntegerField(blank=True, default=120),
        ),
    ]
