# Generated by Django 2.1.2 on 2019-03-25 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('donor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=17)),
                ('pblood_group', models.CharField(choices=[('B+', 'B+'), ('A-', 'A-'), ('A+', 'A+'), ('O+', 'O+'), ('O-', 'O-')], default='B+', max_length=32)),
                ('pgender', models.CharField(default='Male', max_length=32)),
                ('phospital', models.CharField(default='CMC', max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='managedonation',
            name='patient_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.Patient'),
        ),
    ]
